language: python

branches:
  only:
    - master

python:
  - "3.6"
env:
  - PYTORCH_VERSION=master
  - PYTORCH_VERSION=dummy  # Just a hack to make sure th matrix runs

install:
  - if [[ $PYTORCH_VERSION != "dummy" ]]; then
      pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html;
      python setup.py build develop;
    fi

script:
  - if [[ $PYTORCH_VERSION != "dummy" ]]; then
      python -c "import torch; print('PyTorch Version:', torch.__version__)";
      python -m unittest discover;
    else
      echo "Dummy build";
    fi

matrix:
  include:
    - env: LINT_CHECK
      python: "3.6"
      install: pip install flake8 flake8-print
      script: flake8
